### ISSUE TITLE
License

### ISSUE THREAD

**Issue by blanchg** [nickpack/keycloak-sms-authenticator#2]
Hello,

Which license is this under?

Thanks

**Comment by nickpack** [comment]
I'll have to ask the original author that this fork is based on, I tend to licence my own stuff as MIT.

@gwallet Can you confirm licence on your original code please?

**Comment by gwallet** [comment]
Hello,

Unfortunately not, I'm not the original author of keycloak-sms-authenticator, I forked PDrenth/keycloak-sms-authenticator which does not exist anymore … :/

let's ping @PDrenth and @jmjansen

**Comment by Fenrikur** [comment]
Can we assume that this licensing issue has been resolved by @gwallet adding the Eclipse Public License to his project (b7d6949b3ff1a0e83814cc2a0b501bfe7f93846b) from which this one had been forked?

If so, would you mind applying the EPL to your fork as well @nickpack? :)

**Comment by nickpack** [comment]
@Fenrikur @blanchg Done - Commit for the licence has been cherry picked.
